# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/stow/cmake/cmake-3.10.2/bin/cmake

# The command to remove a file.
RM = /usr/local/stow/cmake/cmake-3.10.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/u0920663/CS3505/spreadsheet/server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/u0920663/CS3505/spreadsheet/server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/stow/cmake/cmake-3.10.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/stow/cmake/cmake-3.10.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/u0920663/CS3505/spreadsheet/server/CMakeFiles /home/u0920663/CS3505/spreadsheet/server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/u0920663/CS3505/spreadsheet/server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server_test

# Build rule for target.
server_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server_test
.PHONY : server_test

# fast build rule for target.
server_test/fast:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/build
.PHONY : server_test/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

src/controller/data_container.o: src/controller/data_container.cpp.o

.PHONY : src/controller/data_container.o

# target to build an object file
src/controller/data_container.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/data_container.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/data_container.cpp.o
.PHONY : src/controller/data_container.cpp.o

src/controller/data_container.i: src/controller/data_container.cpp.i

.PHONY : src/controller/data_container.i

# target to preprocess a source file
src/controller/data_container.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/data_container.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/data_container.cpp.i
.PHONY : src/controller/data_container.cpp.i

src/controller/data_container.s: src/controller/data_container.cpp.s

.PHONY : src/controller/data_container.s

# target to generate assembly for a file
src/controller/data_container.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/data_container.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/data_container.cpp.s
.PHONY : src/controller/data_container.cpp.s

src/controller/main_controller.o: src/controller/main_controller.cpp.o

.PHONY : src/controller/main_controller.o

# target to build an object file
src/controller/main_controller.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/main_controller.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/main_controller.cpp.o
.PHONY : src/controller/main_controller.cpp.o

src/controller/main_controller.i: src/controller/main_controller.cpp.i

.PHONY : src/controller/main_controller.i

# target to preprocess a source file
src/controller/main_controller.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/main_controller.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/main_controller.cpp.i
.PHONY : src/controller/main_controller.cpp.i

src/controller/main_controller.s: src/controller/main_controller.cpp.s

.PHONY : src/controller/main_controller.s

# target to generate assembly for a file
src/controller/main_controller.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/main_controller.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/main_controller.cpp.s
.PHONY : src/controller/main_controller.cpp.s

src/controller/network/network_controller.o: src/controller/network/network_controller.cpp.o

.PHONY : src/controller/network/network_controller.o

# target to build an object file
src/controller/network/network_controller.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/network/network_controller.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/network/network_controller.cpp.o
.PHONY : src/controller/network/network_controller.cpp.o

src/controller/network/network_controller.i: src/controller/network/network_controller.cpp.i

.PHONY : src/controller/network/network_controller.i

# target to preprocess a source file
src/controller/network/network_controller.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/network/network_controller.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/network/network_controller.cpp.i
.PHONY : src/controller/network/network_controller.cpp.i

src/controller/network/network_controller.s: src/controller/network/network_controller.cpp.s

.PHONY : src/controller/network/network_controller.s

# target to generate assembly for a file
src/controller/network/network_controller.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/network/network_controller.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/network/network_controller.cpp.s
.PHONY : src/controller/network/network_controller.cpp.s

src/controller/network/tcp_server.o: src/controller/network/tcp_server.cpp.o

.PHONY : src/controller/network/tcp_server.o

# target to build an object file
src/controller/network/tcp_server.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/network/tcp_server.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/network/tcp_server.cpp.o
.PHONY : src/controller/network/tcp_server.cpp.o

src/controller/network/tcp_server.i: src/controller/network/tcp_server.cpp.i

.PHONY : src/controller/network/tcp_server.i

# target to preprocess a source file
src/controller/network/tcp_server.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/network/tcp_server.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/network/tcp_server.cpp.i
.PHONY : src/controller/network/tcp_server.cpp.i

src/controller/network/tcp_server.s: src/controller/network/tcp_server.cpp.s

.PHONY : src/controller/network/tcp_server.s

# target to generate assembly for a file
src/controller/network/tcp_server.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/network/tcp_server.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/network/tcp_server.cpp.s
.PHONY : src/controller/network/tcp_server.cpp.s

src/controller/spreadsheet/formula_parser.o: src/controller/spreadsheet/formula_parser.cpp.o

.PHONY : src/controller/spreadsheet/formula_parser.o

# target to build an object file
src/controller/spreadsheet/formula_parser.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/spreadsheet/formula_parser.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/spreadsheet/formula_parser.cpp.o
.PHONY : src/controller/spreadsheet/formula_parser.cpp.o

src/controller/spreadsheet/formula_parser.i: src/controller/spreadsheet/formula_parser.cpp.i

.PHONY : src/controller/spreadsheet/formula_parser.i

# target to preprocess a source file
src/controller/spreadsheet/formula_parser.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/spreadsheet/formula_parser.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/spreadsheet/formula_parser.cpp.i
.PHONY : src/controller/spreadsheet/formula_parser.cpp.i

src/controller/spreadsheet/formula_parser.s: src/controller/spreadsheet/formula_parser.cpp.s

.PHONY : src/controller/spreadsheet/formula_parser.s

# target to generate assembly for a file
src/controller/spreadsheet/formula_parser.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/spreadsheet/formula_parser.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/spreadsheet/formula_parser.cpp.s
.PHONY : src/controller/spreadsheet/formula_parser.cpp.s

src/controller/spreadsheet/spreadsheet_utils.o: src/controller/spreadsheet/spreadsheet_utils.cpp.o

.PHONY : src/controller/spreadsheet/spreadsheet_utils.o

# target to build an object file
src/controller/spreadsheet/spreadsheet_utils.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/spreadsheet/spreadsheet_utils.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/spreadsheet/spreadsheet_utils.cpp.o
.PHONY : src/controller/spreadsheet/spreadsheet_utils.cpp.o

src/controller/spreadsheet/spreadsheet_utils.i: src/controller/spreadsheet/spreadsheet_utils.cpp.i

.PHONY : src/controller/spreadsheet/spreadsheet_utils.i

# target to preprocess a source file
src/controller/spreadsheet/spreadsheet_utils.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/spreadsheet/spreadsheet_utils.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/spreadsheet/spreadsheet_utils.cpp.i
.PHONY : src/controller/spreadsheet/spreadsheet_utils.cpp.i

src/controller/spreadsheet/spreadsheet_utils.s: src/controller/spreadsheet/spreadsheet_utils.cpp.s

.PHONY : src/controller/spreadsheet/spreadsheet_utils.s

# target to generate assembly for a file
src/controller/spreadsheet/spreadsheet_utils.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/controller/spreadsheet/spreadsheet_utils.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/controller/spreadsheet/spreadsheet_utils.cpp.s
.PHONY : src/controller/spreadsheet/spreadsheet_utils.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/dependency_graph.o: src/model/dependency_graph.cpp.o

.PHONY : src/model/dependency_graph.o

# target to build an object file
src/model/dependency_graph.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/model/dependency_graph.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/model/dependency_graph.cpp.o
.PHONY : src/model/dependency_graph.cpp.o

src/model/dependency_graph.i: src/model/dependency_graph.cpp.i

.PHONY : src/model/dependency_graph.i

# target to preprocess a source file
src/model/dependency_graph.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/model/dependency_graph.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/model/dependency_graph.cpp.i
.PHONY : src/model/dependency_graph.cpp.i

src/model/dependency_graph.s: src/model/dependency_graph.cpp.s

.PHONY : src/model/dependency_graph.s

# target to generate assembly for a file
src/model/dependency_graph.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/model/dependency_graph.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/model/dependency_graph.cpp.s
.PHONY : src/model/dependency_graph.cpp.s

src/model/spreadsheet.o: src/model/spreadsheet.cpp.o

.PHONY : src/model/spreadsheet.o

# target to build an object file
src/model/spreadsheet.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/model/spreadsheet.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/model/spreadsheet.cpp.o
.PHONY : src/model/spreadsheet.cpp.o

src/model/spreadsheet.i: src/model/spreadsheet.cpp.i

.PHONY : src/model/spreadsheet.i

# target to preprocess a source file
src/model/spreadsheet.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/model/spreadsheet.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/model/spreadsheet.cpp.i
.PHONY : src/model/spreadsheet.cpp.i

src/model/spreadsheet.s: src/model/spreadsheet.cpp.s

.PHONY : src/model/spreadsheet.s

# target to generate assembly for a file
src/model/spreadsheet.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/src/model/spreadsheet.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/model/spreadsheet.cpp.s
.PHONY : src/model/spreadsheet.cpp.s

test/controller/spreadsheet/test_formula_parser.o: test/controller/spreadsheet/test_formula_parser.cpp.o

.PHONY : test/controller/spreadsheet/test_formula_parser.o

# target to build an object file
test/controller/spreadsheet/test_formula_parser.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/controller/spreadsheet/test_formula_parser.cpp.o
.PHONY : test/controller/spreadsheet/test_formula_parser.cpp.o

test/controller/spreadsheet/test_formula_parser.i: test/controller/spreadsheet/test_formula_parser.cpp.i

.PHONY : test/controller/spreadsheet/test_formula_parser.i

# target to preprocess a source file
test/controller/spreadsheet/test_formula_parser.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/controller/spreadsheet/test_formula_parser.cpp.i
.PHONY : test/controller/spreadsheet/test_formula_parser.cpp.i

test/controller/spreadsheet/test_formula_parser.s: test/controller/spreadsheet/test_formula_parser.cpp.s

.PHONY : test/controller/spreadsheet/test_formula_parser.s

# target to generate assembly for a file
test/controller/spreadsheet/test_formula_parser.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/controller/spreadsheet/test_formula_parser.cpp.s
.PHONY : test/controller/spreadsheet/test_formula_parser.cpp.s

test/model/test_dependency_graph.o: test/model/test_dependency_graph.cpp.o

.PHONY : test/model/test_dependency_graph.o

# target to build an object file
test/model/test_dependency_graph.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/model/test_dependency_graph.cpp.o
.PHONY : test/model/test_dependency_graph.cpp.o

test/model/test_dependency_graph.i: test/model/test_dependency_graph.cpp.i

.PHONY : test/model/test_dependency_graph.i

# target to preprocess a source file
test/model/test_dependency_graph.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/model/test_dependency_graph.cpp.i
.PHONY : test/model/test_dependency_graph.cpp.i

test/model/test_dependency_graph.s: test/model/test_dependency_graph.cpp.s

.PHONY : test/model/test_dependency_graph.s

# target to generate assembly for a file
test/model/test_dependency_graph.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/model/test_dependency_graph.cpp.s
.PHONY : test/model/test_dependency_graph.cpp.s

test/model/test_spreadsheet.o: test/model/test_spreadsheet.cpp.o

.PHONY : test/model/test_spreadsheet.o

# target to build an object file
test/model/test_spreadsheet.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/model/test_spreadsheet.cpp.o
.PHONY : test/model/test_spreadsheet.cpp.o

test/model/test_spreadsheet.i: test/model/test_spreadsheet.cpp.i

.PHONY : test/model/test_spreadsheet.i

# target to preprocess a source file
test/model/test_spreadsheet.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/model/test_spreadsheet.cpp.i
.PHONY : test/model/test_spreadsheet.cpp.i

test/model/test_spreadsheet.s: test/model/test_spreadsheet.cpp.s

.PHONY : test/model/test_spreadsheet.s

# target to generate assembly for a file
test/model/test_spreadsheet.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/model/test_spreadsheet.cpp.s
.PHONY : test/model/test_spreadsheet.cpp.s

test/test_main.o: test/test_main.cpp.o

.PHONY : test/test_main.o

# target to build an object file
test/test_main.cpp.o:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/test_main.cpp.o
.PHONY : test/test_main.cpp.o

test/test_main.i: test/test_main.cpp.i

.PHONY : test/test_main.i

# target to preprocess a source file
test/test_main.cpp.i:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/test_main.cpp.i
.PHONY : test/test_main.cpp.i

test/test_main.s: test/test_main.cpp.s

.PHONY : test/test_main.s

# target to generate assembly for a file
test/test_main.cpp.s:
	$(MAKE) -f CMakeFiles/server_test.dir/build.make CMakeFiles/server_test.dir/test/test_main.cpp.s
.PHONY : test/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... server_test"
	@echo "... server"
	@echo "... src/controller/data_container.o"
	@echo "... src/controller/data_container.i"
	@echo "... src/controller/data_container.s"
	@echo "... src/controller/main_controller.o"
	@echo "... src/controller/main_controller.i"
	@echo "... src/controller/main_controller.s"
	@echo "... src/controller/network/network_controller.o"
	@echo "... src/controller/network/network_controller.i"
	@echo "... src/controller/network/network_controller.s"
	@echo "... src/controller/network/tcp_server.o"
	@echo "... src/controller/network/tcp_server.i"
	@echo "... src/controller/network/tcp_server.s"
	@echo "... src/controller/spreadsheet/formula_parser.o"
	@echo "... src/controller/spreadsheet/formula_parser.i"
	@echo "... src/controller/spreadsheet/formula_parser.s"
	@echo "... src/controller/spreadsheet/spreadsheet_utils.o"
	@echo "... src/controller/spreadsheet/spreadsheet_utils.i"
	@echo "... src/controller/spreadsheet/spreadsheet_utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model/dependency_graph.o"
	@echo "... src/model/dependency_graph.i"
	@echo "... src/model/dependency_graph.s"
	@echo "... src/model/spreadsheet.o"
	@echo "... src/model/spreadsheet.i"
	@echo "... src/model/spreadsheet.s"
	@echo "... test/controller/spreadsheet/test_formula_parser.o"
	@echo "... test/controller/spreadsheet/test_formula_parser.i"
	@echo "... test/controller/spreadsheet/test_formula_parser.s"
	@echo "... test/model/test_dependency_graph.o"
	@echo "... test/model/test_dependency_graph.i"
	@echo "... test/model/test_dependency_graph.s"
	@echo "... test/model/test_spreadsheet.o"
	@echo "... test/model/test_spreadsheet.i"
	@echo "... test/model/test_spreadsheet.s"
	@echo "... test/test_main.o"
	@echo "... test/test_main.i"
	@echo "... test/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

